# Generated by Django 4.0.3 on 2022-03-07 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_measure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measure',
            old_name='name',
            new_name='amount',
        ),
    ]
