# Generated by Django 4.0.3 on 2022-03-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_fooditem_rename_amount_measure_name_step_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='food_items',
            field=models.ManyToManyField(blank=True, null=True, to='recipes.fooditem'),
        ),
    ]
